### ISSUE TITLE
Regression: internals require API that is not always defined

### ISSUE THREAD

**Issue by danielballan** [intake/intake#545]
It seems as if not all Catalogs implement `_container`, and so this change

```diff
-            return e(name=key)
+            if e._container == 'catalog':
+                return e(name=key)
+            return e()
```

in https://github.com/intake/intake/commit/4aa561c86503d609ed73a5ae9c7e9256b6560bb4 creates some issues. Here's a minimal reproducible example using only built-in intake objects.

```py
In [1]: import pandas

In [2]: df = pandas.DataFrame({'a': [1,2,3], 'b': [4,5,6]})

In [3]: df.to_csv('file.csv')

In [4]: from intake.source.csv import CSVSource

In [5]: from intake import Catalog
/home/dallan/Repos/bnl/intake/intake/__init__.py:43: UserWarning: deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog
 If you want to open a generic URL, you should use intake.open_catalog
  warnings.warn('deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog\n '

In [6]: catalog = Catalog.from_dict({'stuff': CSVSource('file.csv')})

In [7]: catalog['stuff']
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-ad23fb20a5f6> in <module>
----> 1 catalog['stuff']

~/Repos/bnl/intake/intake/catalog/base.py in __getitem__(self, key)
    386             e._catalog = self
    387             e._pmode = self.pmode
--> 388             if e._container == 'catalog':
    389                 return e(name=key)
    390             return e()

AttributeError: 'CSVSource' object has no attribute '_container'
```

We see the same issue with databroker's Catalogs. I haven't found a workaround yet (chasing that in https://github.com/bluesky/databroker/pull/619). It seems worth fixing upstream anyway.

**Comment by danielballan** [comment]
And, to be clear, the above example works fine on intake 0.6.0.

```py
In [4]: catalog['stuff']
Out[4]: 
sources:
  csv:
    args:
      urlpath: file.csv
    description: ''
    driver: intake.source.csv.CSVSource
    metadata: {}

In [5]: catalog['stuff'].read()
Out[5]: 
   Unnamed: 0  a  b
0           0  1  4
1           1  2  5
2           2  3  6
```

**Comment by danielballan** [comment]
I did ultimately find a workaround in https://github.com/bluesky/databroker/pull/619, but that doesn't fix `Catalog` or `YAMLFilesCatalog` (etc.) so we should address this upstream.

**Comment by martindurant** [comment]
Does the following fix it?
```diff
--- a/intake/catalog/base.py
+++ b/intake/catalog/base.py
@@ -37,6 +37,7 @@ class Catalog(DataSource):
     # emulate a DataSource
     container = 'catalog'
     name = 'catalog'
+    auth = None
```

**Comment by danielballan** [comment]
I think that would fix #543. Would it affect this?

**Comment by martindurant** [comment]
Sorry, wrong one indeed. Guess we have a few small bits and pieces.

**Comment by danielballan** [comment]
No worries. Really appreciate your effort. :heart:

**Comment by martindurant** [comment]
Back to the original question, actually the usage is wrong, `from_dict` expects {name: entry}, not {name: source}; but it would be totally reasonable to wrap any source in a basic entry to make this work. Does that sound OK?

**Comment by danielballan** [comment]
I was using (well, **mis**-using) `from_dict` in an attempt to build an SSCCE, but it isn't actually involved the test failures that first brought this to my attention in databroker. Let me try to contrive a more accurate SSCCE before we make any changes to intake.
